- name: Install Apache on Redhat Server
  yum: pkg=httpd state=latest

- name: Start apache services
  service: name=httpd state=started

- name: Install Java 1.7
  yum: name=java-1.7.0-openjdk state=present

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.61/bin/apache-tomcat-7.0.61.tar.gz dest=/opt/apache-tomcat-7.0.61.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-7.0.61.tar.gz -C /opt/ creates=/opt/apache-tomcat-7.0.61

- name: start tomcat services
  shell: nohup /opt/apache-tomcat-7.0.61/bin/startup.sh

